# Generated by Django 5.2.3 on 2025-06-19 08:55

import cats.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='video',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=cats.models.video_upload_path),
        ),
    ]
